spring.datasource.url=jdbc:postgresql://dpg-d72os06a2pns73f48tag-a.virginia-postgres.render.com:5432/postgres_server_vv1g
spring.datasource.username=postgres_server_vv1g_user
spring.datasource.password=UDjTDPk1xCW3y9y9Y3GRM2WiORk6GYCg
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=false

spring.thymeleaf.cache=false
spring.thymeleaf.encoding=UTF-8

spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=5MB
app.cv.upload-dir=./uploads/cv

server.port=8080